-- GrowthPath initial schema (AI-generated plans).
-- Generated by drizzle-kit from lib/db/schema.ts.
--
-- `auth.users` already exists in any Supabase project (managed by Supabase
-- Auth) so we do NOT create it here — we only reference it via FKs.

CREATE TYPE "public"."learning_style" AS ENUM('videos', 'reading', 'projects', 'mixed');--> statement-breakpoint
CREATE TYPE "public"."plan_source" AS ENUM('ai-generated', 'template');--> statement-breakpoint
CREATE TYPE "public"."plan_status" AS ENUM('generating', 'active', 'paused', 'completed', 'archived');--> statement-breakpoint
CREATE TYPE "public"."resource_type" AS ENUM('article', 'video', 'doc', 'exercise', 'course');--> statement-breakpoint
CREATE TYPE "public"."task_category" AS ENUM('technical', 'personal-growth', 'checkpoint');--> statement-breakpoint
CREATE TABLE "completions" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"user_id" uuid NOT NULL,
	"task_id" uuid NOT NULL,
	"plan_id" uuid NOT NULL,
	"week_number" integer NOT NULL,
	"completed_at" timestamp with time zone DEFAULT now() NOT NULL,
	"energy_level" integer,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	CONSTRAINT "completions_energy_level_range" CHECK ("completions"."energy_level" IS NULL OR "completions"."energy_level" BETWEEN 1 AND 5)
);
--> statement-breakpoint
CREATE TABLE "energy_logs" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"user_id" uuid NOT NULL,
	"task_id" uuid NOT NULL,
	"rating" integer NOT NULL,
	"at" timestamp with time zone DEFAULT now() NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	CONSTRAINT "energy_logs_rating_range" CHECK ("energy_logs"."rating" BETWEEN 1 AND 5)
);
--> statement-breakpoint
CREATE TABLE "plan_weeks" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"plan_id" uuid NOT NULL,
	"week_number" integer NOT NULL,
	"month_number" integer NOT NULL,
	"theme" text NOT NULL,
	"goal" text NOT NULL,
	"tasks_generated_at" timestamp with time zone,
	"generation_version" integer DEFAULT 1 NOT NULL,
	"adjustment_notes" text,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL,
	CONSTRAINT "plan_weeks_week_number_range" CHECK ("plan_weeks"."week_number" BETWEEN 1 AND 52),
	CONSTRAINT "plan_weeks_month_number_range" CHECK ("plan_weeks"."month_number" BETWEEN 1 AND 12)
);
--> statement-breakpoint
CREATE TABLE "plans" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"user_id" uuid NOT NULL,
	"title" text NOT NULL,
	"topic" text,
	"goal" text,
	"current_level" text,
	"hours_per_day" integer,
	"learning_style" "learning_style",
	"duration_weeks" integer NOT NULL,
	"source" "plan_source" DEFAULT 'ai-generated' NOT NULL,
	"status" "plan_status" DEFAULT 'generating' NOT NULL,
	"start_date" timestamp with time zone DEFAULT now() NOT NULL,
	"generation_version" integer DEFAULT 1 NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL,
	CONSTRAINT "plans_duration_weeks_range" CHECK ("plans"."duration_weeks" BETWEEN 1 AND 52),
	CONSTRAINT "plans_hours_per_day_range" CHECK ("plans"."hours_per_day" IS NULL OR "plans"."hours_per_day" BETWEEN 1 AND 12)
);
--> statement-breakpoint
CREATE TABLE "profiles" (
	"user_id" uuid PRIMARY KEY NOT NULL,
	"name" text,
	"image" text,
	"early_access" boolean DEFAULT false NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "recaps" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"user_id" uuid NOT NULL,
	"plan_id" uuid NOT NULL,
	"week_number" integer NOT NULL,
	"content" text NOT NULL,
	"achievements" jsonb DEFAULT '[]'::jsonb NOT NULL,
	"growth_areas" jsonb DEFAULT '[]'::jsonb NOT NULL,
	"improvements" jsonb DEFAULT '[]'::jsonb NOT NULL,
	"model_used" text NOT NULL,
	"share_token" text,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL,
	CONSTRAINT "recaps_share_token_unique" UNIQUE("share_token"),
	CONSTRAINT "recaps_week_number_range" CHECK ("recaps"."week_number" BETWEEN 1 AND 52)
);
--> statement-breakpoint
CREATE TABLE "resources" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"task_id" uuid NOT NULL,
	"curated" jsonb DEFAULT '[]'::jsonb NOT NULL,
	"search" jsonb DEFAULT '[]'::jsonb NOT NULL,
	"community" jsonb DEFAULT '[]'::jsonb NOT NULL,
	"ttl_days" integer DEFAULT 30 NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL,
	CONSTRAINT "resources_task_id_unique" UNIQUE("task_id")
);
--> statement-breakpoint
CREATE TABLE "settings" (
	"key" text PRIMARY KEY NOT NULL,
	"value" text NOT NULL,
	"updated_by" uuid,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "tasks" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"plan_id" uuid NOT NULL,
	"plan_week_id" uuid NOT NULL,
	"week_number" integer NOT NULL,
	"month_number" integer NOT NULL,
	"section" text NOT NULL,
	"title" text NOT NULL,
	"body" text DEFAULT '' NOT NULL,
	"category" "task_category" NOT NULL,
	"order" integer NOT NULL,
	"estimated_minutes" integer DEFAULT 30 NOT NULL,
	"generation_version" integer DEFAULT 1 NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL,
	CONSTRAINT "tasks_week_number_range" CHECK ("tasks"."week_number" BETWEEN 1 AND 52),
	CONSTRAINT "tasks_month_number_range" CHECK ("tasks"."month_number" BETWEEN 1 AND 12)
);
--> statement-breakpoint
CREATE TABLE "wins" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"user_id" uuid NOT NULL,
	"plan_id" uuid NOT NULL,
	"week_number" integer NOT NULL,
	"entries" jsonb NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL,
	CONSTRAINT "wins_week_number_range" CHECK ("wins"."week_number" BETWEEN 1 AND 52),
	CONSTRAINT "wins_entries_shape" CHECK (jsonb_array_length("wins"."entries") = 3)
);
--> statement-breakpoint
ALTER TABLE "completions" ADD CONSTRAINT "completions_user_id_users_id_fk" FOREIGN KEY ("user_id") REFERENCES "auth"."users"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "completions" ADD CONSTRAINT "completions_task_id_tasks_id_fk" FOREIGN KEY ("task_id") REFERENCES "public"."tasks"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "completions" ADD CONSTRAINT "completions_plan_id_plans_id_fk" FOREIGN KEY ("plan_id") REFERENCES "public"."plans"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "energy_logs" ADD CONSTRAINT "energy_logs_user_id_users_id_fk" FOREIGN KEY ("user_id") REFERENCES "auth"."users"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "energy_logs" ADD CONSTRAINT "energy_logs_task_id_tasks_id_fk" FOREIGN KEY ("task_id") REFERENCES "public"."tasks"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "plan_weeks" ADD CONSTRAINT "plan_weeks_plan_id_plans_id_fk" FOREIGN KEY ("plan_id") REFERENCES "public"."plans"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "plans" ADD CONSTRAINT "plans_user_id_users_id_fk" FOREIGN KEY ("user_id") REFERENCES "auth"."users"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "profiles" ADD CONSTRAINT "profiles_user_id_users_id_fk" FOREIGN KEY ("user_id") REFERENCES "auth"."users"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "recaps" ADD CONSTRAINT "recaps_user_id_users_id_fk" FOREIGN KEY ("user_id") REFERENCES "auth"."users"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "recaps" ADD CONSTRAINT "recaps_plan_id_plans_id_fk" FOREIGN KEY ("plan_id") REFERENCES "public"."plans"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "resources" ADD CONSTRAINT "resources_task_id_tasks_id_fk" FOREIGN KEY ("task_id") REFERENCES "public"."tasks"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "settings" ADD CONSTRAINT "settings_updated_by_users_id_fk" FOREIGN KEY ("updated_by") REFERENCES "auth"."users"("id") ON DELETE set null ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "tasks" ADD CONSTRAINT "tasks_plan_id_plans_id_fk" FOREIGN KEY ("plan_id") REFERENCES "public"."plans"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "tasks" ADD CONSTRAINT "tasks_plan_week_id_plan_weeks_id_fk" FOREIGN KEY ("plan_week_id") REFERENCES "public"."plan_weeks"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "wins" ADD CONSTRAINT "wins_user_id_users_id_fk" FOREIGN KEY ("user_id") REFERENCES "auth"."users"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "wins" ADD CONSTRAINT "wins_plan_id_plans_id_fk" FOREIGN KEY ("plan_id") REFERENCES "public"."plans"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
CREATE UNIQUE INDEX "completions_user_task_unique" ON "completions" USING btree ("user_id","task_id");--> statement-breakpoint
CREATE UNIQUE INDEX "completions_user_plan_week_idx" ON "completions" USING btree ("user_id","plan_id","week_number","task_id");--> statement-breakpoint
CREATE UNIQUE INDEX "plan_weeks_plan_week_unique" ON "plan_weeks" USING btree ("plan_id","week_number");--> statement-breakpoint
CREATE UNIQUE INDEX "recaps_user_plan_week_unique" ON "recaps" USING btree ("user_id","plan_id","week_number");--> statement-breakpoint
CREATE UNIQUE INDEX "tasks_plan_week_order_unique" ON "tasks" USING btree ("plan_week_id","order");--> statement-breakpoint
CREATE UNIQUE INDEX "wins_user_plan_week_unique" ON "wins" USING btree ("user_id","plan_id","week_number");